### ISSUE TITLE
TPM "could not load TCTI; device or resource busy"

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#176]
Key error phrases:
`Failed to open specified TCTI device file`
`Device or resource busy`
`Could not initialize TCTI file`
`Failed to instantiate TCTI`

Happens when: running `keylime_ima_emulator`

Output:
```
[root@localhost ~]# keylime_ima_emulator
Using config file /etc/keylime.conf
2021-03-24 17:24:45.029 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
Traceback (most recent call last):
  File "/usr/local/bin/keylime_ima_emulator", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_ima_emulator')())
  File "/usr/local/bin/keylime_ima_emulator", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/cmd/ima_emulator_adapter.py", 
line 17, in <module> tpm_instance = tpm(need_hw_tpm=True)
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/tpm/tpm_main.py", line 228,
 in __init__self.__startup_tpm()
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/tpm/tpm_main.py", line 385, 
in __startup_tpm retDict = self.__run(['tpm2_startup', '-c'])
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/tpm/tpm_main.py", line 375, 
in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, 
retout, reterr)) Exception: Command: ['tpm2_startup', '-c'] returned 1, expected 0, output [], 
stderr [b'ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open specified 
TCTI device file /dev/tpm1: Device or resource busy \n', b'WARNING:tcti:src/tss2-tcti/tctildr.c:79:
tcti_from_init() TCTI init for function 0x7f7c892e0950 failed with a000a \n', b'WARNING:tcti:src/tss2-
tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device \n', b'ERROR:tcti:src/tss2-
\tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: device \n', b'ERROR:tcti:src/tss2-tcti/
tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI \n', b'ERROR: Could not load tcti, got: 
"device:/dev/tpm1"\n']
```

**Comment by lkatalin** [comment]
Solution: kill and restart the swtpm.

```
[root@localhost ~]# ps aux | grep swtpm
root        2593  0.0  0.1   7332  3304 ?        Ss   17:23   0:00 swtpm chardev --tpm2 --vtpm-proxy --tpmstate dir=/var/vtpm -d
root        2810  0.0  0.0 221432   788 pts/0    S+   17:39   0:00 grep --color=auto swtpm
[root@localhost ~]# kill 2593
[root@localhost ~]# ./swtpm.sh 
Found existing /var/vtpm
New TPM device: /dev/tpm2 (major/minor = 253/2)
[root@localhost ~]# ls /dev/tpm*
/dev/tpm0  /dev/tpm2  /dev/tpmrm0  /dev/tpmrm2
[root@localhost ~]# export TPM2TOOLS_TCTI="device:/dev/tpm2"
[root@localhost ~]# keylime_ima_emulator
Using config file /etc/keylime.conf
...
```
