### ISSUE TITLE
With hardware TPM: Resetting the TPM emulator may be necessary

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#177]
Occurs when: Running `keylime_ima_emulator` using hardware TPM in F33VM

Error output:
```
[root@localhost ~]# ls /dev/tpm*
/dev/tpm0  /dev/tpmrm0
[root@localhost ~]# echo $TCTI
device:/dev/tpm0
[root@localhost ~]# echo $TPM2TOOLS_TCTI 
device:/dev/tpm0
[root@localhost ~]# keylime_ima_emulator
Using config file /etc/keylime.conf
2021-03-24 18:28:13.180 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
Warning: IMA PCR is not empty, trying to find the last updated file in the measurement list...
Traceback (most recent call last):
  File "/usr/local/bin/keylime_ima_emulator", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_ima_emulator')())
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/cmd/ima_emulator_adapter.py", line 87, in main
    pos = ml_extend(config.IMA_ML, 0, pcrval)
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/cmd/ima_emulator_adapter.py", line 70, in ml_extend
    raise Exception(
Exception: Unable to find current measurement list position, Resetting the TPM emulator may be neccesary
```

**Comment by lkatalin** [comment]
Thanks to @puiterwijk for insight on this error:
This occurs because the hardware TPM is also used by the kernel, which means PCR 10 is not empty (the kernel always extends a boot summary digest), and the emulator refuses.
