### ISSUE TITLE
Python Keylime agent startup error: Failed to instantiate TCTI

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#178]
Occurs when: Running the Python `keylime_agent` on a VM that is running the emulator, verifier, and registrar with `swtpm`. The emulator is using `TPM2TOOLS_TCTI="device:/dev/tpm1"`

Key error phrases:
`Failed to open specified TCTI device file`
`Device or resource busy`
`Could not initialize TCTI `
`Could not load TCTI `

Error output:
```
[root@localhost ~]# keylime_agent
Using config file /etc/keylime.conf
2021-03-24 18:48:49.249 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
2021-03-24 18:48:49.269 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
2021-03-24 18:48:49.273 - keylime.secure_mount - INFO - mounting secure storage location /var/lib/keylime/
secure on tmpfs
2021-03-24 18:48:49.326 - keylime.tpm - WARNING - INSECURE: Keylime is using a software TPM emulator rather 
than
 a real hardware TPM.
2021-03-24 18:48:49.326 - keylime.tpm - WARNING - INSECURE: The security of Keylime is NOT linked to a hardware 
root of trust.
2021-03-24 18:48:49.326 - keylime.tpm - WARNING - INSECURE: Only use Keylime in this mode for testing or 
debugging purposes.
2021-03-24 18:48:49.327 - keylime.tpm - INFO - Taking ownership with config provided TPM owner password
2021-03-24 18:48:49.408 - keylime.tpm - INFO - TPM Owner password confirmed: keylime
2021-03-24 18:48:49.408 - keylime.tpm - INFO - Flushing old ek handle: 0x81000000
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')())
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/cmd/agent.py", line 15, 
in main keylime_agent.main()
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/keylime_agent.py", line 481, 
in main (ekcert, ek_tpm, aik_tpm) = instance_tpm.tpm_init(self_activate=False, config_pw=config.get(
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/tpm/tpm_main.py", line 894, 
in tpm_init self.__create_ek()
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/tpm/tpm_main.py", line 413, 
in __create_ek
    raise Exception("tpm2_getcap failed with code " + str(code) + ": " + str(reterr))
Exception: tpm2_getcap failed with code 1: [b'ERROR:tcti:src/tss2-tcti/tcti-device.c:440:
Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm1: Device or resource busy
\n', b'WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f562bba8950 
failed with a000a \n', b'WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI 
named: tcti-device \n', b'ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI
 file: device \n', b'ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate
TCTI \n', b'ERROR: Could not load tcti, got: "device:/dev/tpm1"\n']
```

Could be related to #176

**Comment by lkatalin** [comment]
Solution:
Export the resource manager version of the TPM device:
`export TPM2TOOLS_TCTI="device:/dev/tpmrm1"` AND NOT the version the emulator is using `device:/dev/tpm1`

Then run the `keylime_agent`

**Comment by arthurus-rex** [comment]
I received these same error messages and this fix still works, but with some minor additions:

1.   Check the name of the TPM in the `/dev` folder.  On my device it was /dev/tpmrm0, so the command that worked was `export TPM2TTOOLS_TCTI="device:/dev/tpmrm0`.
2.   You may need to restart the emulators using  ` systemctl restart ima_emulator ` and/or `systemctl restart tpm_emulator`.  If it works, expect a nonzero hash at the `sha256, line 10` when checking registers with  `tpm2_pcrread`.

This fix is also works in the [ansible Keylime deployment](https://github.com/keylime/keylime-vagrant-ansible-tpm-emulator).
