### ISSUE TITLE
Tenant connection terminated

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#188]
```
[root@localhost ~]# keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -f /root/excludes.txt --uuid 
D432FBB3-D2F1-4A97-9EF7-75BD81C00000 --allowlist /root/allowlist.txt --exclude 
/root/excludes.txt -c add
Using config file /etc/keylime.conf
2021-05-06 15:14:17.371 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
2021-05-06 15:14:17.373 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-05-06 15:14:17.373 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-05-06 15:14:17.373 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS 
request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: 
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Terminated

```

**Comment by lkatalin** [comment]
Specifically, this tends to happen during a `delete` command from the tenant:

```
[root@localhost ~]# keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -f /root/excludes.txt --uuid d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist /root/allowlist.txt --exclude /root/excludes.txt -c delete
Using config file /etc/keylime.conf
2021-07-05 08:52:31.596 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
2021-07-05 08:52:31.600 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib64/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.9/site-packages/urllib3/packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib64/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_tenant')())
  File "/usr/local/lib/python3.9/site-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 1203, in main
    mytenant.do_cvdelete(args.verifier_check)
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 654, in do_cvdelete
    agent_json = self.do_cvstatus(listing=False, returnresponse=True)
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 611, in do_cvstatus
    response = do_cvstatus.get(
  File "/usr/local/lib/python3.9/site-packages/keylime/requests_client.py", line 29, in get
    return self.session.get(self.base_url + url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

My current workaround is to not use the delete command and instead delete the databases manually to prepare for a fresh re-add of the agent:

```
[root@localhost keylime]# pwd
/var/lib/keylime
[root@localhost keylime]# rm *.sqlite
rm: remove regular file 'cv_data.sqlite'? y
rm: remove regular file 'reg_data.sqlite'? y
```

... but surely there is a better way. I believe this probably originates in the Python components (the tenant is interacting with the CV here) so I will check to make sure there is an open issue on that side.

**Comment by lkatalin** [comment]
It seems like this no longer occurs.
