### ISSUE TITLE
keylime agent supplies malformed quote to verifier when there is no IMA log in the system

### ISSUE THREAD

**Issue by galmasi** [keylime/rust-keylime#380]
Environment
--

Verifier/Registrar: v6.4.0 standard, running on an Ubuntu 20.04 substrate with docker containers.
Keylime Agent: 
    * rust agent commit c8343943b23a64d9a7b378e1a4bb2251832f76fc (Wed May 11, "CI: Add packit ...")
     * OS: OpenBMC "phosphor" running on a qemu-emulated cortex A7.
     * kernel `5.14.6-yocto-s-dirty-7ae156b` with _IMA disabled_.
     * The problem can be reproduced in any agent where the IMA log is missing/unreadable.

Symptom
--

Keylime verifier fails upon first attestation attempt with the following message:

```
2022-05-18 17:27:23.266 - keylime.cloudverifier - ERROR - ima_measurement_list_entry parameter must be an integer
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime-6.4.0-py3.9.egg/keylime/cloud_verifier_tornado.py", line 810, in invoke_get_quote
    failure = cloud_verifier_common.process_quote_response(agent, json_response['results'], agentAttestState)
  File "/usr/local/lib/python3.9/site-packages/keylime-6.4.0-py3.9.egg/keylime/cloud_verifier_common.py", line 73, in process_quote_response
    raise Exception("ima_measurement_list_entry parameter must be an integer")
Exception: ima_measurement_list_entry parameter must be an integer
```

Root cause
--

The culprit is line 261 in `src/quotes_handler.rs`. This line returns the triplet of ima measurement list, line entry and number of entries in a situation where the IMA list was not found by the agent.

The current implementation returns a "None" in this situation, which translates to `NoneType` on the verifier side. However, the verifier seems to insist on this value *always* being an integer, and throws an uncaught exception when sent a `None` instead.

A trivial fix to the problem on the keylime agent side would be to send replace `None` with `Some(0)` in this situation. Thus:

```
diff --git a/src/quotes_handler.rs b/src/quotes_handler.rs
index 6654882..4206c58 100644
--- a/src/quotes_handler.rs
+++ b/src/quotes_handler.rs
@@ -258,7 +258,7 @@ pub async fn integrity(
                 }
             }
         } else {
-            (None, None, None)
+            (None, Some(0), None)
         };
 
```

This seems to fix the immediate problem. 

Potential PR
--

git branch `fix-no-ima-log` on the fork `https://github.com/galmasi/rust-keylime.git` is available to create a PR. I will do so if you ask for it. But the proposed fix is trivial enough that you may just want to do it yourself -- I'll follow suit.

Extra testing?
--

Clearly the rust agent is not unit tested in a situation where the IMA log is missing. Please consider adding a test for the situation where the IMA log is missing.

**Comment by ansasaki** [comment]
This is partially a bug on the verifier side which cannot handle the `None` value for an optional field, effectively making it a required field. I'll open an issue there for this.

Anyway, I'll make the proposed change and add a test for it.

**Comment by ansasaki** [comment]
> This is partially a bug on the verifier side which cannot handle the `None` value for an optional field, effectively making it a required field. I'll open an issue there for this.
> 
> Anyway, I'll make the proposed change and add a test for it.

I take this back. The real issue is that `serde` does not behave as I expected, which is to skip serializing optional fields when the value is `None` by default. From the [documentation](https://docs.rs/serde_with/1.13.0/serde_with/attr.skip_serializing_none.html), I have to explicitly make the serialization to skip such fields by adding a `#[skip_serializing_none]` annotation.

I'll add this to all structures with optional fields.

**Comment by galmasi** [comment]
+1 Thank you for the quick action on this matter. I agree that not sending optional fields is much better than sending "syntactically compliant nonsense".

There is an additional problem involving the transmission of IMA logs. @maugustosilva raised this yesterday during the initial discussion of this bug, but I'll mention it here and make it a separate issue if you agree. The observation is that you should not attempt to transmit the IMA log if the verifier is not asking for it, even if it exists, as a matter of privacy and performance both. Looking at the code in the agent, is it fair to say that it will transmit the IMA log if it exists, no matter whether the verifier is asking for it or not?

-- George

**Comment by ansasaki** [comment]
> +1 Thank you for the quick action on this matter. I agree that not sending optional fields is much better than sending "syntactically compliant nonsense".
> 
> There is an additional problem involving the transmission of IMA logs. @maugustosilva raised this yesterday during the initial discussion of this bug, but I'll mention it here and make it a separate issue if you agree. The observation is that you should not attempt to transmit the IMA log if the verifier is not asking for it, even if it exists, as a matter of privacy and performance both. Looking at the code in the agent, is it fair to say that it will transmit the IMA log if it exists, no matter whether the verifier is asking for it or not?
> 
> -- George

If I understood this correctly, the proposal is to modify the agent behavior to send the IMA log following some kind of policy, is this correct? Would something similar to what is done with the measured boot acceptable (i.e. to send the log depending on the provided PCR mask)? In any case, I think this level of change needs to follow the enhancement proposal process.
